version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=i_nevakshenov@mail.ru
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --api.insecure=false
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/acme.json:/acme.json
      - ./traefik-users.txt:/etc/traefik/traefik-users.txt # Файл с кэшами паролей
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.calc.press`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=le"

      # Добавляем middleware с аутентификацией
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/traefik-users.txt"

      # Дополнительно: добавляем security headers
      - "traefik.http.middlewares.auth.basicauth.removeheader=true"
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
    name: traefik_proxy-network