# docker-compose.proxy.yml
version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy_certs:/etc/nginx/certs
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - proxy-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: letsencrypt_companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy_certs:/etc/nginx/certs
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=i_nevakshenov@mail.ru
      - NGINX_PROXY_CONTAINER=nginx_proxy
    networks:
      - proxy-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  proxy_certs:
  proxy_html:
  proxy_vhost:

networks:
  proxy-network:
    driver: bridge
    name: proxy_proxy-network